# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-02 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('location', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Company',
                'verbose_name': 'Company',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.CharField(default='', max_length=100)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'concepts',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Institution Name')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Concept')),
            ],
            options={
                'verbose_name_plural': 'Project TPConcept',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='CreateDate')),
                ('description_analysis', models.TextField(blank=True, null=True, verbose_name='Job Description Analysis')),
                ('concepts', models.ManyToManyField(through='brightStafferapp.ProjectConcept', to='brightStafferapp.Concept')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recruiter ID')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'verbose_name': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('talent_name', models.CharField(default='', max_length=100, verbose_name='Talent Name')),
                ('current_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Location')),
                ('email_id', models.EmailField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Email Id')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='CreateDate')),
            ],
            options={
                'verbose_name_plural': 'Talent',
                'verbose_name': 'Talent',
                'db_table': 'talent',
            },
        ),
        migrations.CreateModel(
            name='TalentCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Currently Working Here')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Company')),
                ('talent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Talent', verbose_name='Talent')),
            ],
            options={
                'verbose_name_plural': 'Talent Work History',
                'db_table': 'talent_company_tb',
            },
        ),
        migrations.CreateModel(
            name='TalentConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Concept')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Talent')),
            ],
            options={
                'verbose_name_plural': 'Talent TPConcept',
            },
        ),
        migrations.CreateModel(
            name='TalentEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Education')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Talent')),
            ],
            options={
                'verbose_name_plural': 'Talent Education History',
            },
        ),
        migrations.CreateModel(
            name='TalentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_match', models.CharField(blank=True, max_length=20, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('Contacted', 'Contacted'), ('Replied', 'Replied'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Under Review', 'Under Review'), ('Scheduled For Interview', 'Scheduled For Interview'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], max_length=50)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Projects')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Talent')),
            ],
            options={
                'verbose_name_plural': 'Talent Projects',
            },
        ),
        migrations.AddField(
            model_name='talent',
            name='company',
            field=models.ManyToManyField(through='brightStafferapp.TalentCompany', to='brightStafferapp.Company'),
        ),
        migrations.AddField(
            model_name='talent',
            name='concepts',
            field=models.ManyToManyField(through='brightStafferapp.TalentConcept', to='brightStafferapp.Concept'),
        ),
        migrations.AddField(
            model_name='talent',
            name='education',
            field=models.ManyToManyField(through='brightStafferapp.TalentEducation', to='brightStafferapp.Education'),
        ),
        migrations.AddField(
            model_name='talent',
            name='project',
            field=models.ManyToManyField(through='brightStafferapp.TalentProject', to='brightStafferapp.Projects'),
        ),
        migrations.AddField(
            model_name='talent',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recruiter ID'),
        ),
        migrations.AddField(
            model_name='projectconcept',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Projects'),
        ),
    ]
