# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepts', models.TextField(blank=True, null=True, verbose_name='Job Concepts')),
            ],
            options={
                'verbose_name_plural': 'Concepts',
                'db_table': 'concepts',
                'verbose_name': 'Concepts',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('recuriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recuriter ID')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'verbose_name': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='concepts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Projects', verbose_name='Project ID'),
        ),
    ]
