# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=125, verbose_name='User_Name')),
                ('user_password', models.TextField(max_length=125, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'BrightStaffer_Login',
                'verbose_name_plural': 'BrightStaffer_Login',
                'db_table': 'brightStaffer_login',
            },
        ),
    ]
