# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept', models.TextField(blank=True, null=True, verbose_name='Job Concept')),
            ],
            options={
                'verbose_name_plural': 'Concepts',
                'verbose_name': 'Concept',
                'db_table': 'concepts',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('is_published', models.TextField(default=False, verbose_name='Published')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='CreateDate')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recruiter ID')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'verbose_name': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.Projects', verbose_name='Project ID'),
        ),
    ]
