# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=125, verbose_name='User_Name')),
                ('last_name', models.TextField(max_length=125, verbose_name='Last Name')),
                ('user_password', models.TextField(max_length=125, verbose_name='Password')),
                ('confirm_passsword', models.TextField(max_length=125, verbose_name='Password')),
                ('email', models.TextField(max_length=125, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'user_signup',
                'db_table': 'user_signup',
                'verbose_name_plural': 'user_signup',
            },
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
