# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0001_brightstaffer_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
    ]
