# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0001_custom_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentconcept',
            options={'verbose_name_plural': 'Talent Concepts'},
        ),
        migrations.AddField(
            model_name='talent',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='industry_focus',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='linkdein_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Active', 'Active')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='talentconcept',
            name='match',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='talent',
            name='email_id',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='talentcompany',
            name='talent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_company', to='brightStafferapp.Talent', verbose_name='Talent'),
        ),
        migrations.AlterField(
            model_name='talentconcept',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_concepts', to='brightStafferapp.Talent'),
        ),
        migrations.AlterField(
            model_name='talentproject',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_project', to='brightStafferapp.Talent'),
        ),
    ]
