# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0002_0001_brightstaffer_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='is_published',
            field=models.TextField(default=False, verbose_name='Published'),
        ),
    ]
