# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0002_auto_20161111_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='confirm_passsword',
            field=models.TextField(max_length=125, verbose_name='Confirm Password'),
        ),
    ]
