# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0002_auto_20170303_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='concepts',
            field=models.ManyToManyField(blank=True, null=True, through='brightStafferapp.TalentConcept', to='brightStafferapp.Concept'),
        ),
    ]
