# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 12:42
from __future__ import unicode_literals

import brightStafferapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brightStafferapp', '0003_auto_20170303_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('file', models.FileField(upload_to=brightStafferapp.models.get_upload_file_dir)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PdfImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(max_length=500, upload_to=brightStafferapp.models.get_image_file_dir)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brightStafferapp.FileUpload')),
            ],
        ),
    ]
