# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0003_auto_20161111_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_signup',
            old_name='confirm_passsword',
            new_name='confirm_password',
        ),
    ]
