# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0004_auto_20161111_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_signup',
        ),
    ]
