# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0004_fileupload_pdfimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
