# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0005_auto_20170303_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='alternate_email_id',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Alternate Email Id'),
        ),
        migrations.AddField(
            model_name='talent',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
