# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0006_auto_20170306_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='linkdein_url',
            new_name='linkedin_url',
        ),
    ]
