# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightStafferapp', '0007_auto_20170306_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentcompany',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
